name: 03 Sequential Jobs

on:
  workflow_dispatch:  # Se ejecuta manualmente

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        run: echo "Running linting..."

  unit_tests:
    runs-on: ubuntu-latest
    needs: linting   # Espera a que termine linting
    steps:
      - name: Unit Tests
        run: echo "Running unit tests..."

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests   # Espera a que terminen las pruebas unitarias
    steps:
      - name: Set Up Test Environment
        run: echo "Setting up test environment..."

      - name: Integration Tests
        run: echo "Running integration tests..."
